services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    image: tiktokbot:latest
    container_name: tiktokbot-container
    volumes:
      - .:/project
      - ./data:/project/data
      - ./audio:/project/audio
      - ./video:/project/video
    environment:
      - PYTHONPATH=/project  
    command: ["python", "main.py"]