services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    image: tiktokbot:latest
    container_name: tiktokbot-container
    volumes:
      - .:/project
      - ./data:/project/data
      - ./data/audio:/project/data/audio
      - ./data/video:/project/data/video
      - ./data/text:/project/data/text
    environment:
      - PYTHONPATH=/project  
    command: ["python", "main.py"]